on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
       steps:
         - uses: actions/checkout@v2
         - uses: actions/setup-node@v2
         - run: npm -v
